name: octocoin
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  freezed: ^2.5.2
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  dartz: ^0.10.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  mockito: ^5.4.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
