name: octocoin
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  freezed: ^2.0.4
  dio: ^4.0.6
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  dartz: ^0.10.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  mockito: ^5.2.0
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
